Selenium tests updates (#98)
* Make tests use the actual version of Likely instead of specifically generated one

I’ve made a stupid mistake: all tests were ran against a customly-generated version of Likely hosted in gh-pages. This made all the CI integration just meaningless. This commit fixes this.

I tried to use `file://` urls initially, but this was resulting in a `TypeError: this.browser.getBrowserForTab is not a function` error, so I had to use a local HTTP server instead.

* Use the npm geckodriver instance

Usable after https://github.com/vladikoff/node-geckodriver/pull/7

* Use the common 20s timeout for _everything_ in tests

* Add pre-tasks for building and testing

Also, remove Travis’ `before-script` as it’s not necessary anymore

* Configure the `prepublish` script to run only when publishing

Currently, the script is also run on `npm install` (by design; see https://github.com/npm/npm/issues/10074). It’s undesirable:
* the tests are run twice, and the build time increases
* if the tests fail, the build errors (because `npm install` fails) instead of a fail

* Fix the code style